server:
 port: 9151    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: vamshi33333
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: dialect:org.hibernate.dialect.MySQL8Dialect
  